link : list main item_int queue_list
	gcc list.o main.o item_int.o queue_list.o -o eseguibilie.exe

list :
	gcc -c list.c

item_int :
	gcc -c item_int.c

main :
	gcc -c main.c

queue_list :
	gcc -c queue_list.c

clean :
	del list.o main.o item_int.o queue_list.o eseguibilie.exe
