link: list main item_int stack queue
	gcc list.o main.o item_int.o stack.o queue.o -o a.out

main:
	gcc -c main.c

queue:
	gcc -c queue.c

item_int:
	gcc -c item_int.c

item_string:
	gcc -c item_string.c

stack:
	gcc -c stack.c

list:
	gcc -c list.c

clean:
	rm *.o a.out
