link : main itemCar car list utils
	gcc main.o itemCar.o car.o list.o utils.o -o car.exe

main :
	gcc -c main.c

itemCar :
	gcc -c itemCar.c

car :
	gcc -c car.c

list :
	gcc -c list.c

utils :
	gcc -c utils.c

clean :
	del *.o *.exe