link: list main item_string stack queue_stack 
	gcc list.o main.o item_string.o stack_list.o queue_stack.o -o queue

list :
	gcc -c list.c

item_int :
	gcc -c item_int.c

item_string :
	gcc -c item_string.c

main :
	gcc -c main.c

queue_list :
	gcc -c queue_list.c

queue_array :
	gcc -c queue_array.c

queue_stack :
	gcc -c queue_stack.c

stack:
	gcc -c stack_list.c

clean :
	del list.o main.o item_int.o item_string.o queue_array.o queue_stack.o queue_list.o stack_list.o queue.exe
