link : list stack btree item main
	gcc list.o stack.o btree.o item.o main.o -o a.out

btree :
	gcc -c btree.c

stack :
	gcc -c stack.c

list  :
	gcc -c list.c

item :
	gcc -c item_int.c -o item.o

main :
	gcc -c main.c

clean :
	rm *.o a.out
